### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by uraway** [uraway/react-native-mybrowser#1]
- [ ] Reload button
- [ ] Resize footer
- [ ] Loading spinner
- [ ] Disabled button style
- [x] Navigator in AddressBar
- [x] fix goBack Button
